### PR TITLE
fix: add `repository` field to Cargo.toml

### PR DESCRIPTION
**Pull request by smoelius**
To make the repository easier to find. Apologies if this field was omitted intentionally.

### CODE REVIEW

**Comment by scrabsha** [comment]
That is an excellent idea, thanks for suggesting it!

One small nit: can you define the `repository` field in the `[workspace.package]` section and then add a `repository.workspace = true` in every package in the repo?

**Comment by smoelius** [comment]
If this is not what you had in mind, feel free to edit my branch. Thanks!

**Comment by scrabsha** [comment]
Thanks! And sorry for taking this long to work on your PR

**Comment by smoelius** [comment]
NP. Cheers!

**Pull request merged**
